## Dekompozicija matrice kamere na unutrasnju i spoljasnju matricu

### Zadatak 1 - Nadji koordinate centra kamere

Napisati Python 3 funkciju centar(T)  koja za datu 3x4 matricu kamere T,  tipa np.array, vraća homogene koordinate centra kamere (sa 1 na poslednjoj koordinati), 4-vektor, tipa np.array.


ulaz je tipa np.array. Izlaz je tipa np.array, u formatu, recimo C = np.array([2,-1,4,1])
kod  np.set_printoptions(precision=5, suppress=True)  ostaviti uključen kako bi izlaz bio formatiran na pravi način. 
Kao i ranije: da biste izbegli -0.  izlaz možete koristiti kod  C = np.where(np.isclose(C, 0) , 0.0 , C)
Unutar jednog pokušaja za prvu grešku gubite 0%, za drugu 0%, za treću 20%...

In [1]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
 
def centar(T):
 
 # vaš kod
    C1 = np.linalg.det(np.delete(T, 0, 1))
    C2 = np.linalg.det(np.delete(T, 1, 1))
    C3 = np.linalg.det(np.delete(T, 2, 1))
    C4 = np.linalg.det(np.delete(T, 3, 1))
    C = np.array([C1, -C2, C3, -C4])/(-C4)
 
    C = np.where(np.isclose(C, 0) , 0.0 , C)
    return C
 

### Zadatak 2 - Unutrasnja matrica kamere - K

Napisati Python 3 funkciju kameraK(T)  koja za datu 3x4 matricu kamere T,  tipa np.array, 3x3 matricu K kalibracije kamere, tipa np.array.


ulaz i izlaz su  tipa np.array
matricu kamere K formatirati tako da K[2,2] = 1 (donje desno polje, tj. pozicija (3,3)).
ukoliko imate netačan rezultat zbog negativnih dijagonalnih vrednosti matrice K (a time i A) pogledajete uputstvo na glavnoj strani. 
kod  np.set_printoptions(precision=5, suppress=True)  ostaviti uključen kako bi izlaz bio formatiran na pravi način. 
Kao i ranije: da biste izbegli -0.  izlaz možete koristiti kod  K = np.where(np.isclose(K, 0) , 0 , K),  neposredno pre vracanja rezultata.
Penalty regime 0,0,20,40,60,80,100 (vidi iznad) znači da unutar jednog pokušaja za prvu grešku gubite 0%, za drugu 0%, za treću 20%...

In [7]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
 
def kameraK(T):
 
 # vaš kod
    t0 = np.delete(T, 3, 1) # 1- kolona, 0 - vrsta
    # ako je det t0 <0 onda T-> -T
    if np.linalg.det(t0) < 0:
        T = -T
        t0 = np.delete(T, 3, 1)
        
    t0inverz = np.linalg.inv(t0)
    
    # QR dekompozicija t0inverz
    Q, R = np.linalg.qr(t0inverz)

    if(R[0,0] < 0):
        R = np.matmul(np.diag([-1, 1, 1]), R)
        Q = np.matmul(Q, np.diag([-1, 1, 1]))
    if(R[1,1] < 0):
        R = np.matmul(np.diag([1, -1, 1]), R)
        Q = np.matmul(Q, np.diag([1, -1, 1]))
    if(R[2,2] < 0):
        R = np.matmul(np.diag([1, 1, -1]), R)
        Q = np.matmul(Q, np.diag([1, 1, -1]))
        
    K = np.linalg.inv(R)
    K = K / K[2, 2]
 
    K = np.where(np.isclose(K, 0) , 0.0 , K)
    return K
 

#### Test primeri

In [4]:
T = np.array([[-2,3,0,7], [-3,0,3,-6], [1,0,0,-2]])
print(kameraK(T))

[[ 3.  0. -2.]
 [ 0.  3. -3.]
 [ 0.  0.  1.]]


In [5]:
T=np.array([[5, -1-2*10, 3, 18-3*10], [0,-1, 5, 21], [0, -1, 0,1]])
print(kameraK(T))

[[ 5.  3. 21.]
 [ 0.  5.  1.]
 [ 0.  0.  1.]]


In [6]:
T2 = np.array([[-40.76114 , 96.88137  , 5.02608 , 257.87105],
 [-80.7022 , -30.26509 , 64.822  , 433.86004],
 [ -0.02538 , -0.00392 , -0.01387 ,  1.     ]])
print(kameraK(T2))

[[3538.64709  -65.06268  686.74666]
 [   0.      3382.03034 1488.20067]
 [   0.         0.         1.     ]]


### Zadatak 3 - Spoljasnja  matrica kamere - A

Napisati Python 3 funkciju kameraA(T)  koja za datu 3x4 matricu kamere T,  tipa np.array, 3x3 matricu A  spoljašnih parametara kamere, tipa np.array.


ulaz i izlaz su  tipa np.array
kod  np.set_printoptions(precision=5, suppress=True)  ostaviti uključen kako bi izlaz bio formatiran na pravi način. 
Kao i ranije: da biste izbegli -0.  izlaz možete koristiti kod  A = np.where(np.isclose(A, 0) , 0.0 , A)
Ukoliko imate problem sa negativnim dijagonalnim vrednostima matrice K (a time i netačnu matricu A) pročitajte uputstvo (glavna strana).
Unutar jednog pokušaja za prvu grešku gubite 0%, za drugu 0%, za treću 20%...

In [10]:
import numpy as np
from numpy import linalg
import math
np.set_printoptions(precision=5, suppress=True) 
 
 # ovde pišete pomocne funkcije
 
def kameraA(T):
 
 # vaš kod
    t0 = np.delete(T, 3, 1) # 1- kolona, 0 - vrsta
    if np.linalg.det(t0) < 0:
        T = -T
        t0 = np.delete(T, 3, 1)
        
    t0inverz = np.linalg.inv(t0)
    
    # QR dekompozicija t0inverz
    Q, R = np.linalg.qr(t0inverz)
    if(R[0,0] < 0):
        R = np.matmul(np.diag([-1, 1, 1]), R)
        Q = np.matmul(Q, np.diag([-1, 1, 1]))
    if(R[1,1] < 0):
        R = np.matmul(np.diag([1, -1, 1]), R)
        Q = np.matmul(Q, np.diag([1, -1, 1]))
    if(R[2,2] < 0):
        R = np.matmul(np.diag([1, 1, -1]), R)
        Q = np.matmul(Q, np.diag([1, 1, -1]))
    A = Q
 
    A = np.where(np.isclose(A, 0) , 0.0 , A)
    return A
 

#### Test primeri

In [12]:
T = np.array([[-2,3,0,7], [-3,0,3,-6], [1,0,0,-2]])
print(kameraA(T))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [13]:
T=np.array([[5, -1-2*10, 3, 18-3*10], [0,-1, 5, 21], [0, -1, 0,1]])
print(kameraA(T))

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [14]:
T2 = np.array([[-40.76114 , 96.88137  , 5.02608 , 257.87105],
 [-80.7022 , -30.26509 , 64.822  , 433.86004],
 [ -0.02538 , -0.00392 , -0.01387 ,  1.     ]])
print(kameraA(T2))

[[ 0.2339   0.43492  0.86956]
 [-0.95953  0.2475   0.13431]
 [-0.15681 -0.86579  0.47521]]


### Zadatak 4

Napisati Python 3 funkciju matricaKamere(pts2D, pts3D)  koja za date nizove odgovarajućih tačaka,  tipa np.array, jednake dužine bar 6, vraća 3x4 matricu kamere T, tipa np.array, koja projektuje tačke pts3D redom u tačke pts2D.


ulaz su dva niza tačaka, jednake dužine najmanje 6, tipa np.array. Recimo:
pts2D=np.array([[120, 11,44], [15,24,2], ...])
pts3D=np.array([[17, 18,19,1], [150,214,25,5], ...]) 
izlaz je matrica T formata 3x4, normalizovana tako da je T(3,4) = 1
kod  np.set_printoptions(precision=5, suppress=True)  ostaviti uključen kako bi izlaz bio formatiran na pravi način. 
Kao i ranije: da biste izbegli -0.  izlaz možete koristiti kod  T = np.where(np.isclose(T, 0) , 0.0 , T)
Unutar jednog pokušaja za prvu grešku gubite 0%, za drugu 0%, za treću 20%...

In [24]:
import numpy as np
from numpy import linalg
import math

np.set_printoptions(precision=5, suppress=True)


# ovde pišete pomocne funkcije

def sistem(img, org):
    nula = np.array([0, 0, 0, 0])
    x1 = np.array(np.concatenate((nula, -img[2]*org, img[1]*org)))
    x2 = np.array(np.concatenate((img[2]*org, nula, -img[0]*org)))
    return [x1, x2]

def matricaA(imgs, origs):
    A = []
    for i in range(len(imgs)):
        img = imgs[i]
        org = origs[i]
        A.extend(sistem(img, org))
    return A

def matricaKamere(pts2D, pts3D):
    # vaš kod
    A = matricaA(pts2D, pts3D)
    A = np.array(A)

    U, S, V = np.linalg.svd(A)
    T = V[11]
    
    T = T/T[11]
    
    T = T.reshape(3, 4)
    T = np.where(np.isclose(T, 0), 0.0, T)
    return T

#### Test primeri

#### Test primeri

In [25]:
pts2D = np.array([[12, 61, 31], [1, 95, 4], [20, 82, 19], [56, 50, 55], [32, 65, 84], [46, 39, 16], [67, 63, 78]])
pts3D = np.array([[44, 61, 31, 99], [17, 84, 40, 45], [20, 59, 65, 3], [37, 81, 70, 82], [7, 95, 8, 29], [31, 61, 91, 37], [82, 99, 80, 7]])
print(matricaKamere(pts2D,pts3D))

[[-4.95933 -0.2536   1.79307  1.09047]
 [-6.93112  0.0049   3.79892 -0.21861]
 [-5.88155 -0.39931  2.34601  1.     ]]


In [22]:
pts2D = np.array([[12, 61, 31], [1, 95, 4], [20, 82, 19], [56, 50, 55], [32, 65, 84], [46, 39, 16], [67, 63, 78]])
pts3D = np.array([[44, 61, 31, 99], [17, 84, 40, 45], [20, 59, 65, 3], [37, 81, 70, 82], [7, 95, 8, 29], [31, 61, 91, 37], [82, 99, 80, 7]])
print(matricaKamere(pts2D,pts3D))

[[-4.95933 -0.2536   1.79307  1.09047]
 [-6.93112  0.0049   3.79892 -0.21861]
 [-5.88155 -0.39931  2.34601  1.     ]]


In [23]:
projs = np.array([[91,284, 1], [179,595, 1], [407,507,1],[310,170,1], [539,147,1], [637,467,1], [191,356,1],[420, 272,1]] )
origs = np.array([[0,0, 3,1], [0, 3,3,1], [3,3,3,1],[3, 0,3,1], [3, 0,0,1], [3, 3,0,1],[1,1,3,1],[3,1,2,1]] )
print(matricaKamere(projs, origs))

[[ 61.7356   27.33275 -75.21323 313.21916]
 [-40.75192  96.87713   5.01128 257.8699 ]
 [ -0.02536  -0.00392  -0.01392   1.     ]]
