In [1]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

def opstiPolozaj(matr):    
    A = matr[0]
    B = matr[1]
    C = matr[2]
    D = matr[3]
    m1 = [A, B, C]
    m2 = [A, B, D]
    m3 = [A, C, D]
    m4 = [B, C, D]
    
    # Calculate the determinants
    det_m1 = np.linalg.det(m1)
    det_m2 = np.linalg.det(m2)
    det_m3 = np.linalg.det(m3)
    det_m4 = np.linalg.det(m4)

    if(det_m1 > 0 and det_m1 < 0.000001):
        det_m1 = 0
        
    if(det_m2 > 0 and det_m2 < 0.000001):
        det_m2 = 0
    if(det_m3 > 0 and det_m3 < 0.000001):
        det_m3 = 0
    if(det_m4 > 0 and det_m4 < 0.000001):
        det_m4 = 0

        
        
    if det_m1 == 0 or det_m2 == 0 or det_m3 == 0 or det_m4 == 0:
        return False
    
    return True

def find_matrix(pts):
    matrix = np.array([ # A, B, C
        [pts[0][0], pts[1][0], pts[2][0]],
        [pts[0][1], pts[1][1], pts[2][1]],
        [pts[0][2], pts[1][2], pts[2][2]]
    ])

    D = np.array([pts[3][0], pts[3][1], pts[3][2]])

    # D = alpha*A + beta*B + gamma*C
    result = np.linalg.solve(matrix, D)

    alpha = result[0]
    beta = result[1]
    gamma = result[2]

    column1= np.array([alpha*pts[0][0], alpha*pts[0][1], alpha*pts[0][2]])
    column2= np.array([beta*pts[1][0], beta*pts[1][1], beta*pts[1][2]])
    column3= np.array([gamma*pts[2][0], gamma*pts[2][1], gamma*pts[2][2]])

    P = np.column_stack([column1, column2, column3])

    return P
 
def naivni(origs, imgs):
 
 # vaš kod
 
    if(not opstiPolozaj(origs)):
        return "Losi originali!"

    if(not opstiPolozaj(imgs)):
        return "Lose slike!"
    
    P1 = find_matrix(origs)
    P2 = find_matrix(imgs)

    # P = P2*inv(P1)
    P = np.dot(P2, np.linalg.inv(P1))
    
    for i in range(3):
        for j in range(3):
            if(P[i][j] < 0 and P[i][j] > -0.000001):
                P[i][j] = 0
                
    if(P[2][2] != 1 and P[2][2] != 0):
        P = P/P[2][2]
        
    return P

In [2]:
	
trapez = [[- 3, - 1, 1], [3, - 1, 1], [1, 1, 1], [- 1, 1, 1]]
pravougaonik = [[- 2, - 1, 1], [2, - 1, 1], [2, 1, 1], [- 2, 1, 1]]
print(naivni(trapez, pravougaonik))

[[ 1.   0.   0. ]
 [ 0.   1.  -0.5]
 [ 0.  -0.5  1. ]]


In [3]:
origs = [[- 3, - 1, 1], [3, - 1, 1], [1, 1, 1], [- 1, 1, 1]]
imgs = [[- 2, - 5, 1], [2, - 5, 1], [2, 1, 1], [6, -3, 3]]   #primetite da nisu u opstem polozaju
print(naivni(origs, imgs))

Lose slike!


In [4]:
print(naivni([[868, 2, 1],[410, 10, 1], [1278, 813, 3], [499, 222, 1]], [[567,934, 1], [394, 110, 1], [535, 777, 1], [169, 694, 1]]))

[[ -0.22485  -1.08182 352.39009]
 [  0.39702  -0.49459 -88.20882]
 [ -0.00083  -0.00264   1.     ]]


In [5]:
print(naivni([[799, 381, 609], [13, 669, 501], [820, 516, 435], [1619, 897, 1044]], [[466, 985, 130], [724, 453, 166], [626, 294, 943], [157, 822, 136]]))

Losi originali!


In [6]:
opstiPolozaj([[466, 985, 130], [724, 453, 166], [626, 294, 943], [157, 822, 136]])

True

In [7]:
print(naivni([[466, 985, 130], [724, 453, 166], [626, 294, 943], [157, 822, 136]], [[799, 381, 609], [13, 669, 501], [820, 516, 435], [1619, 897, 1044]]))

Lose slike!
